apiVersion: apps/v1
kind: Deployment
metadata:
  name: insurance-app
  labels:
    app: insurance-app
spec:
  replicas: 3
  selector:
    matchLabels:
      app: insurance-app
  template:
    metadata:
      labels:
        app: insurance-app
    spec:
      containers:
      - name: insurance-app
        image: vivekguatam07/insurance-app
        ports:
        - containerPort: 8081
---
apiVersion: v1
kind: Service
metadata:
  name: insurance-app
  labels:
    app: insurance-app
spec:
  selector:
    app: insurance-app

  type: NodePort
  ports:
  - nodePort: 31036 
    port: 8081
    targetPort: 8081
